apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-app-deployment
  namespace: edge
  labels:
    app: edge-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge-app
  template:
    metadata:
      labels:
        app: edge-app
    spec:
      containers:
      - name: edge-app
        image: cimox/edge-app:0.0.2
        ports:
        - containerPort: 5000
        env:
          - name: EDGE_APP_HOST
            value: '0.0.0.0'
          - name: EDGE_APP_PORT
            value: '5000'
---
apiVersion: v1
kind: Service
metadata:
  name: edge-app-service
  namespace: edge
spec:
  selector:
    app: edge-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
